---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: os-cluster
  namespace: default
spec:
  security:
    config:
    tls:
      http:
        generate: true
      transport:
        generate: true
        perNode: true
  general:
    httpPort: 9200
    serviceName: os-cluster
    setVMMaxMapCount: true
    version: 3.0.0
    pluginsList: []
    drainDataNodes: true
  dashboards:
    tls:
      enable: true
      generate: true
    version: 3.0.0
    enable: true
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-nodepool: dashboards-nodepool
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: data
      replicas: 3
      nodeSelector:
        cloud.google.com/gke-nodepool: opensearch-nodepool
      diskSize: "300Gi"
      jvm: -Xmx6G -Xms6G
      resources:
        requests:
          memory: "12Gi"
          cpu: 3
        limits:
          memory: "12Gi"
          cpu: 3
      roles:
        - "data"
        - "cluster_manager"
      persistence:
        pvc:
          storageClass: premium-rwo
          accessModes:
            - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: os-cluster-service
spec:
  type: ClusterIP
  selector:
    opster.io/opensearch-nodepool: data
    #opster.io/os-cluster: os-cluster
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboards-service
spec:
  type: ClusterIP
  selector:
    opensearch.cluster.dashboards: os-cluster
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
